[solution]: zh/medium-diff
ghaiklor/type-challenges-solutions pull request #207
Opened 2022-05-20 13:28 UTC by SUtengda

# Challenge [zh/medium-diff]

## Checklist

- [x] Make sure that you are opening the PR with a single solution (one solution per PR)
- [x] The solution must have at least several references for the readers to dive in depth

2022-05-21 09:11 UTC, ghaiklor requested changes

2022-05-21 09:11 UTC, ghaiklor commented on zh/medium-diff.md
> +lang: en
You need to reflect the language here

```suggestion
lang: zh
```

2022-05-21 09:11 UTC, ghaiklor commented on zh/medium-diff.md
> +When iterating over the properties, we need to check if the property exists on `O` or `O1`.
Missed

2022-05-21 09:23 UTC, SUtengda commented on zh/medium-diff.md
> +lang: en
Corrected. Thanks

2022-05-21 09:24 UTC, SUtengda commented on zh/medium-diff.md
> +When iterating over the properties, we need to check if the property exists on `O` or `O1`.
done

2022-05-22 08:40 UTC, ghaiklor commented
@charleserious is the native to Chinese AF AIU, so we need to get approval of someone like him or himself. In regard to the infra, everything is ok.

2022-05-23 11:23 UTC, SUtengda commented
@ghaiklor  It seems all checks are successful for this PR, could you pls merge it ?

2022-05-23 17:17 UTC, ghaiklor approved these changes

2022-05-23 17:17 UTC, merged

2022-05-24 00:49 UTC, charleserious reviewed
LGTM