[solution]: zh/medium-trim
ghaiklor/type-challenges-solutions pull request #209
Opened 2022-05-22 09:23 UTC by SUtengda

# Challenge [edium-trim]

## Checklist

- [ ] Make sure that you are opening the PR with a single solution (one solution per PR)
- [ ] The solution must have at least several references for the readers to dive in depth

2022-05-24 01:19 UTC, charleserious requested changes
Great work bro~
Issues check below~

2022-05-24 01:19 UTC, charleserious commented on zh/medium-trim.md
> +实现`Trim<T>`，它是一个字符串类型，并返回一个新字符串，其中两端的空白符都已被删除。
I think we can not omit the "takes" here, which will be "它接收一个字符串类型"

2022-05-24 01:19 UTC, charleserious commented on zh/medium-trim.md
> +通过结合模板字面量类型和条件类型，我们可以推断对没有空格的其余部分推断。
duplicated infer translation here, and could be “我可以推断出不包含空字符串的其余部分”

2022-05-24 01:21 UTC, charleserious commented
For the failing check, rebasing the main branch will solve the failure

2022-05-24 20:59 UTC, SUtengda commented on zh/medium-trim.md
> +实现`Trim<T>`，它是一个字符串类型，并返回一个新字符串，其中两端的空白符都已被删除。
you are right, thanks

2022-05-25 07:36 UTC, likui628 approved these changes

2022-05-25 10:26 UTC, ghaiklor approved these changes

2022-05-25 10:27 UTC, ghaiklor commented
Forcing the merge, seems like comments from @charleserious were resolved, and we got another approval.

2022-05-25 10:28 UTC, merged