[solution] uk/medium-absolute
ghaiklor/type-challenges-solutions pull request #53
Opened 2021-06-20 13:57 UTC by shalamai

# Challenge [medium-absolute]

## Checklist

- [ ] Make sure that you are opening the PR with a single solution (one solution per PR)
- [ ] The solution must have at least several references for the readers to dive in depth

2021-06-21 19:38 UTC, bdvorianov commented on uk/medium-absolute.md
> +Він має приймати `string`, `number` or `bigint`. Результатом повинно бути позитивне число у вигляді рядка.
```suggestion
Він має приймати `string`, `number` або `bigint`. Результатом повинно бути позитивне число у вигляді рядка.
```

2021-06-21 19:47 UTC, bdvorianov commented on uk/medium-absolute.md
> +## Рішення
```suggestion
## Розв'язок
```

2021-06-21 19:52 UTC, bdvorianov commented on uk/medium-absolute.md
> +Таким чином, якщо вкажемо `T = “-50”`, це співпаде з нашим шаблоном `“-<N>”` де `N` буде `"50"`, й ми його повернемо.
```suggestion
Таким чином, якщо вкажемо `T = “-50”`, це відповідатиме нашому шаблону `“-<N>”` де `N` буде `"50"`, й ми його повернемо.
```

2021-06-21 19:53 UTC, bdvorianov commented on uk/medium-absolute.md
> +Наприклад, передавши позитивне число, воно не співпаде з рядком в умовному типі й повернеться число замість рядку.
```suggestion
Наприклад, якщо передати позитивне число, воно не збіжиться з рядком в умовному типі й повернеться число замість рядка.
```

2021-06-21 19:54 UTC, bdvorianov commented on uk/medium-absolute.md
> +Число знову не співпадає з нашою умовою, виведення не спрацьовує й ми повертаємо негативне число, тільки в рядку.
```suggestion
Число знову не збігається з нашою умовою, виведення не спрацьовує й ми повертаємо негативне число, тільки в рядку.
```

2021-06-21 19:55 UTC, bdvorianov commented on uk/medium-absolute.md
> +В результаті, ми отримали тип, який приймає `number`, `string`, `bigint` й конвертує їх в рядок.
```suggestion
В результаті, ми отримали тип, який приймає `number`, `string` або `bigint` і конвертує їх в рядок.
```

2021-06-21 19:56 UTC, bdvorianov commented on uk/medium-absolute.md
> +В інакшому випадку, у нас позитивне число, тому повертаємо його без змін:
```suggestion
В інакшому випадку, у нас додатне число, тому повертаємо його без змін:
```

2021-06-21 19:57 UTC, bdvorianov commented on uk/medium-absolute.md
> +Ми не опрацьовуємо випадок, коли `T` це негативне число.
```suggestion
Ми не опрацьовуємо випадок, коли `T` це від'ємне число.
```

2021-06-21 19:59 UTC, bdvorianov requested changes
I've added some suggestions, please take a look. 😇

2021-06-22 05:52 UTC, shalamai commented
agree with all of them, thanks 👍

2021-06-26 06:24 UTC, ghaiklor approved these changes

2021-06-26 06:25 UTC, ghaiklor commented
@bdvorianov your turn, everything is ok with the PR? 🙂

2021-06-26 07:43 UTC, ghaiklor commented
TravisCI are morons, disabling the auto-merge for now.

2021-06-26 08:40 UTC, ghaiklor commented
Migrated to GitHub Actions

2021-07-04 14:17 UTC, ghaiklor commented
@bdvorianov bump

2021-07-08 15:53 UTC, bdvorianov approved these changes

2021-07-08 15:53 UTC, merged